In [1]:
3-2

[1] 1

#simple math R


In [2]:
sin(4)

[1] -0.7568025

In [3]:
4>3

[1] TRUE

In [4]:
4 < 3

[1] FALSE

In [5]:
4 == 3

[1] FALSE

In [6]:
(4 == 4) && (3 > 2)

[1] TRUE

# VARIABLE ASSIGNMENT


In [9]:
a <- 3 + 3

In [10]:
a

[1] 6

In [11]:
print("hey sb")

[1] "hey sb"


In [13]:
some_logic <- TRUE

In [14]:
some_logic

[1] TRUE

### The Vector

In [15]:
dat <- c(4 , 5 , 6, 23, 2)

In [16]:
dat

[1]  4  5  6 23  2

In [20]:
my_vec <- rep(0,10)

In [21]:
my_vec

[1] 0 0 0 0 0 0 0 0 0 0

In [22]:
m <- 1:20

In [23]:
m

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20

In [26]:
v3 <- seq(-10, 10, 2)

In [27]:
v3

[1] -10  -8  -6  -4  -2   0   2   4   6   8  10

In [28]:
show(v3)

 [1] -10  -8  -6  -4  -2   0   2   4   6   8  10


In [29]:
u <- seq(-2, 2,1)

In [30]:
u

[1] -2 -1  0  1  2

## Indexing and Slicing

In [32]:
v<-rnorm(5)

In [33]:
v


[1]  1.0245075  0.9509451 -0.2206364 -0.1487206 -0.2679064

In [34]:
v[2]

[1] 0.9509451

In [35]:
v

[1]  1.0245075  0.9509451 -0.2206364 -0.1487206 -0.2679064

In [36]:
v[1:3]

[1]  1.0245075  0.9509451 -0.2206364

In [37]:
v[2:5]

[1]  0.9509451 -0.2206364 -0.1487206 -0.2679064

In [38]:
v[c(1,3)]

[1]  1.0245075 -0.2206364

In [39]:
v[-3]

[1]  1.0245075  0.9509451 -0.1487206 -0.2679064

# Assignment and Indexing

In [40]:
u <- c(5,6,8,22)

In [41]:
u[1]<-0

In [42]:
u

[1]  0  6  8 22

In [43]:
u3 <- u[1:3]

In [44]:
print(u3)

[1] 0 6 8


In [45]:
v <- c(10, 20, 30)

In [46]:
v[1]<0

[1] FALSE

In [47]:
v[1]<-0
v[2]<-0

In [48]:
v

[1]  0  0 30

In [49]:
v<- seq(10,50,10
       )

In [50]:
v

[1] 10 20 30 40 50

In [51]:
v2<-c(v[1],v[3],v[5])

In [52]:
v2

[1] 10 30 50

In [55]:
v3<- c(TRUE,FALSE, TRUE, FALSE,TRUE) # this is creating a vector
v[v3]

[1] 10 30 50

In [56]:
v <- c(44,55,66)

In [57]:
v-20

[1] 24 35 46

In [58]:
v*2

[1]  88 110 132

In [59]:
v > 50

[1] FALSE  TRUE  TRUE

In [60]:
v >> 50

ERROR: Error in parse(text = x, srcfile = src): <text>:1:4: unexpected '>'
1: v >>
       ^


# Useful Operations on Vectors

In [62]:
v <- rnorm(10)

In [63]:
print(v)

 [1] -2.56790974 -1.35781224  0.02680607  0.54942910  0.97889255 -0.08988467
 [7]  0.25263795  0.89536754 -0.49583611  2.37559056


In [64]:
sum(v)

[1] 0.567281

In [65]:
max(v)

[1] 2.375591

In [66]:
min(v)

[1] -2.56791

In [67]:
sd(v)

[1] 1.351104

# The Matrix

In [68]:
x1<-c(4,5,6)

In [69]:
x2<-c(55,55,57)

In [70]:
m<-cbind(x1,x2)

In [71]:
m   # is a 3x2 matrix

x1 x2
[1,] 4  55
[2,] 5  55
[3,] 6  57

In [72]:
m2<-rbind(x1,x2)

In [73]:
m2

[,1] [,2] [,3]
x1  4    5    6  
x2 55   55   57

In [74]:
a<- matrix(0, nrow=3,ncol=3)

In [75]:
a

[,1] [,2] [,3]
[1,] 0    0    0   
[2,] 0    0    0   
[3,] 0    0    0

In [76]:
print(a)

     [,1] [,2] [,3]
[1,]    0    0    0
[2,]    0    0    0
[3,]    0    0    0


In [77]:
dat <- rnorm(15)

In [78]:
dat

[1]  1.13973412 -0.06798735  0.68336705  0.70059415 -0.35609363 -1.02477513
 [7]  0.11616950  0.57746868  0.74849955 -1.71455608  0.79635021 -0.94958110
[13] -1.24277431 -0.95548131 -0.71054259

In [83]:
b<- matrix("dat",ncol=3,nrow=5)

In [84]:
print(b)

     [,1]  [,2]  [,3] 
[1,] "dat" "dat" "dat"
[2,] "dat" "dat" "dat"
[3,] "dat" "dat" "dat"
[4,] "dat" "dat" "dat"
[5,] "dat" "dat" "dat"


In [85]:
m<- matrix(dat, ncol=3)

In [86]:
m

[,1]        [,2]       [,3]      
[1,]  1.13973412 -1.0247751  0.7963502
[2,] -0.06798735  0.1161695 -0.9495811
[3,]  0.68336705  0.5774687 -1.2427743
[4,]  0.70059415  0.7484995 -0.9554813
[5,] -0.35609363 -1.7145561 -0.7105426

In [87]:
m[1,2]

[1] -1.024775

In [88]:
m[2,3]

[1] -0.9495811

In [89]:
m[1:2 ,3]

[1]  0.7963502 -0.9495811

In [90]:
m[1,]

[1]  1.1397341 -1.0247751  0.7963502

In [91]:
m[,1]

[1]  1.13973412 -0.06798735  0.68336705  0.70059415 -0.35609363

In [92]:
m[,3]<-0

In [93]:
m

[,1]        [,2]       [,3]
[1,]  1.13973412 -1.0247751 0   
[2,] -0.06798735  0.1161695 0   
[3,]  0.68336705  0.5774687 0   
[4,]  0.70059415  0.7484995 0   
[5,] -0.35609363 -1.7145561 0

In [94]:
m[1:2,2]<-99
m

[,1]        [,2]       [,3]
[1,]  1.13973412 99.0000000 0   
[2,] -0.06798735 99.0000000 0   
[3,]  0.68336705  0.5774687 0   
[4,]  0.70059415  0.7484995 0   
[5,] -0.35609363 -1.7145561 0

In [95]:
print(m)

            [,1]       [,2] [,3]
[1,]  1.13973412 99.0000000    0
[2,] -0.06798735 99.0000000    0
[3,]  0.68336705  0.5774687    0
[4,]  0.70059415  0.7484995    0
[5,] -0.35609363 -1.7145561    0


In [96]:
num_rows<-nrow(m)

In [97]:
print(nrows)

ERROR: Error in print(nrows): object 'nrows' not found


In [98]:
num_rows

[1] 5

In [99]:
colmeans(m)

ERROR: Error in colmeans(m): could not find function "colmeans"


In [100]:
colMeans(m)

[1]  0.4199229 39.5222824  0.0000000

In [101]:
colSums(m)

[1]   2.099614 197.611412   0.000000

In [102]:
rowSums(m)

[1] 100.139734  98.932013   1.260836   1.449094  -2.070650

# The DataFrame

In [103]:
id <- seq(4)

In [104]:
id

[1] 1 2 3 4

In [105]:
score<- rnorm(4)

In [106]:
names <- c("john","paul","george","ringo")

In [107]:
vocals<- c(TRUE,TRUE,FALSE,FALSE)
dset<-data.frame(id,names,score,vocals)

In [108]:
dset

id names  score       vocals
1 1  john   -1.41598257  TRUE 
2 2  paul    0.39706834  TRUE 
3 3  george -0.06854374 FALSE 
4 4  ringo   1.35067970 FALSE

In [109]:
dset[1,2]

[1] john
Levels: george john paul ringo

In [110]:
dset$names

[1] john   paul   george ringo 
Levels: george john paul ringo